### ISSUE TITLE
More particle disables (Feature)

### ISSUE THREAD

**Issue by AByakugans** [kodenamekrak/NoParticles#1]
Hello,
Can you aldo add option to disable global particles? Small (dot-like) particles around the map? These options:

Disable Camera Noise
Disable global particle haze

From this PC mode? 

https://github.com/Shadnix-was-taken/BeatSaber-ParticleOverdrive 
or this
https://github.com/kinsi55/BeatSaber_Tweaks55

Thank you!

**Comment by kodenamekrak** [comment]
Hi, I will look into adding this when i have the time, thanks for the suggestion!

**Comment by AByakugans** [comment]
Great - with version 0.1.3 it is no longer in the menu - but it is still in-game with songs can you remove that too, please?

**Comment by kodenamekrak** [comment]
I will try to fix that when the mod is updated for 1.25. (I didnt realise those particles existed in songs until i had already released the updated version💀)

**Comment by kodenamekrak** [comment]
This is now fixed in the 1.25.1 build :)
